### ISSUE TITLE
Quality of life suggestion

### ISSUE THREAD

**Issue by a6avind** [LuD1161/upi-recon-cli#5]
Hey @LuD1161,
Can we add a status check for the API key?

Something like 
```go
resp, err := client.Do(req)

if resp.StatusCode == 401 {
	fmt.Println("[+] <blah blah blah> : "resp.Status)
	os.Exit(0)
}
```

**Comment by a6avind** [comment]
#2 might also be related to API keys

**Comment by LuD1161** [comment]
Thanks for the issue @a6avind 🙌 
Will work on this soon. Or if you want to raise a PR go ahead 😄

**Comment by LuD1161** [comment]
Hey @a6avind 👋 
This is redundant, as the tool doesn't require any key now.
Thanks 😄
